COUNTRIES = sorted([
    "Albania",
    "Argentina",
    "Australia",
    "Azerbaijan",
    "Bahrain",
    "Bangladesh",
    "Belarus",
    "Bosnia and Herzegovina",
    "Brazil",
    "Cambodia",
    "Canada",
    "Chile",
    "China",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Dominican Republic",
    "Egypt",
    "Ethiopia",
    "Georgia",
    "Ghana",
    "Hong Kong",
    "Iceland",
    "India",
    "Indonesia",
    "Ireland",
    "Israel",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kuwait",
    "Laos",
    "Lebanon",
    "Madagascar",
    "Malaysia",
    "Maldives",
    "Mauritius",
    "Mexico",
    "Moldova",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Namibia",
    "Nepal",
    "New Zealand",
    "Nigeria",
    "North Macedonia",
    "Norway",
    "Oman",
    "Peru",
    "Philippines",
    "Qatar",
    "Russia",
    "Rwanda",
    "Saudi Arabia",
    "Serbia",
    "Singapore",
    "South Africa",
    "South Korea",
    "Sri Lanka",
    "Switzerland",
    "Taiwan",
    "Tanzania",
    "Thailand",
    "Tunisia",
    "Turkey",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uzbekistan",
    "Vietnam",
    "Zambia",
    "Zimbabwe"
])
